sudo: required
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xms1g -Xmx3g"
install: ./gradlew setupCIWorkspace -s
script: ./gradlew build -s

notifications:
  email: false
